services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
  localstack:
    image: localstack/localstack
    ports:
      - 4566:4566
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - PORT_WEB_UI=8080
      - LAMBDA_EXECUTOR=docker
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './tmp/localstack:/tmp/localstack'
      - './tmp/lambda:/tmp/lambda:ro'
  maildev:
    build:
      context: .
      dockerfile: maildev.Dockerfile
    ports:
      - ${MAIL_CLIENT_PORT}:1080
      - ${MAIL_PORT}:1025
volumes:
  mongo:
